<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6d5055976ce99d1374e67ea6bd24a554
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Infogram\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Infogram\\' => 
        array (
            0 => __DIR__ . '/..' . '/infogram/infogram/src/Infogram',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Requests' => 
            array (
                0 => __DIR__ . '/..' . '/rmccue/requests/library',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6d5055976ce99d1374e67ea6bd24a554::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6d5055976ce99d1374e67ea6bd24a554::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit6d5055976ce99d1374e67ea6bd24a554::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
